# Generated by Django 4.0.1 on 2022-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='nl_name_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
