# Generated by Django 4.0.1 on 2022-03-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_alter_incidences_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidences',
            name='name',
            field=models.TextField(max_length=250),
        ),
    ]
