# Generated by Django 4.0.1 on 2022-03-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_alter_counties_nl_name_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='varname_2',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
