# Generated by Django 4.0.1 on 2022-03-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_alter_incidences_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidences',
            name='name',
            field=models.TextField(),
        ),
    ]
